### ISSUE TITLE
Error when trying to start with diameters.txt

### ISSUE THREAD

**Issue by anton2tchekov** [VasiliBaranov/packing-generation#25]
Dear Dr. Baranov, 

I am a PhD student working on beads packing. I developed a python script generating dense polydisperse packing in 2D and it works well but now I need a 3D version for the following of my thesis. 

I recently found out your great package that I managed to use to generate monodisperse close packing. However when I tried to use a _diameters.txt_ file with random radii instead of copying packing.xyzd from the Docs folder I get an error that I don't understand. 

The only thing I changed when I generated the solution on VisualStudio is that I commented few lines like these:
_DenseBase<Derived>::segment(Index start, Index size) const
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return ConstSegmentReturnType(derived(), start, size);
}_

The reason was that these gave me some errors (c2373 and c2447) that I did not succeed to correct (I nearly know nothing in C++). Any chance that these lines I commented are the source of my problem?

Thanks a lot!

Antoine Montiel

![Capture](https://user-images.githubusercontent.com/55913211/101619004-f8a02800-3a12-11eb-8231-7909527a87b9.PNG)

**Comment by VasiliBaranov** [comment]
Hi Antoine,

sorry for a long time to reply.

I can only make several wild guesses that may or may not be helpful.

* first, maybe the diameters.txt file has less or more entries than N that you specify in the generation.conf. And maybe the code tries to get diameter number 5500, but the diameters.txt had only 5000 values
* i don't know if you compiled the program yourself or downloaded the compiled version. If you compiled it yourself, maybe there are some issues due to a newer version of the compiler being incompatible with the old version of Eigen that i used back then. I developed the program with Visual Studio 2010 or 2013 i think. The solution will be to use the compiled exe that is available under Releases
  * ah, you probably tried to compile it yourself, then the Eigen version was too old for a new compiler, you encountered the errors, and you commented several lines. Please try the version here https://github.com/VasiliBaranov/packing-generation/releases/tag/v1.0.1.28

If nothing helps, you can also try to use packing.xyzd directly instead of diameters.txt: i.e., you place particles at random positions, but you set their diameters as you intended. Then you put this file instead of diameters.txt. This generation script can be easily written in Python with numpy.

Hope this helps!

Best Regards,
Vasili

**Comment by anton2tchekov** [comment]
Hello Vasili, happy new year, 

Thanks a lot for your help. Finally I managed to use your compiled version and it works perfectly on Windows 10. 
I came to the same conclusions concerning my compiling, I guess the compiler raise some errors because it is a newer version and it does not support anymore the way you coded your algo. 

May I ask you another question? Now I need a Linux version to be used in my calculator. How can I do since until now I used your precompiled .exe? 

Best regards, 

Antoine

**Comment by VasiliBaranov** [comment]
Dear Antoine,

> I guess the compiler raises some errors because it is a newer version and it does not support anymore the way you coded your algo.

Yes, exactly. Though the error seems to come from the library that i used back then, Eigen, https://en.wikipedia.org/wiki/Eigen_(C%2B%2B_library) , http://eigen.tuxfamily.org/index.php?title=Main_Page

> May I ask you another question? Now I need a Linux version to be used in my calculator. How can I do since until now I used your precompiled .exe?

Unfortunately i don't have a precompiled version for Linux, so you unfortunately have to compile it yourself (with the gcc compiler and the make files, see https://github.com/VasiliBaranov/packing-generation/wiki/Compilation and the folder _Release). If you see errors like above, you have several options:
* try to use newer versions of libraries if they also throw errors with a new gcc compiler (the libraries are in the Externals subfolder). But it will be tricky and maybe the libraries changed some APIs, so my code won't work with new versions of libraries
* use an older version of the gcc compiler, from around 2014-2017 - probably the easiest way
* generate the packings on Windows, then run your analysis code on linux

Hope this helps!

Best Regards,
Vasili

**Comment by anton2tchekov** [comment]
Hello Vasili, 

I succeeded to compile your package on Linux using make.
So a big thanks for your help and advice. 

Best regards, 

Antoine
